compile_run:
	javac Juegop/Juego.java Juegop/Personaje.java Juegop/A.java Juegop/B.java 
	java Juegop/Juego
compile_run_2:
	javac Instance/Juego.java Instance/Personaje.java Instance/A.java Instance/B.java 
	java Instance/Juego
